version: '3.8'

services:
  api:
    build: .
    container_name: cut-url-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
      "

  postgres:
    image: postgres:15
    container_name: cut-url-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
