apiVersion: v1
kind: Service
metadata:
  name: cut-url-api
  namespace: cut-url
  labels:
    app: cut-url-api
spec:
  type: NodePort
  selector:
    app: cut-url-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
